"""inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 03:45:49.331051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.Text(), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('licitacion_codigo', sa.String(length=40), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_licitacion_codigo'), ['licitacion_codigo'], unique=False)

    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('regiones', sa.JSON(), nullable=False),
    sa.Column('monto_min', sa.Float(), nullable=True),
    sa.Column('monto_max', sa.Float(), nullable=True),
    sa.Column('palabras_clave', sa.JSON(), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_activo', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('giro', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('token_cuenta_hash', sa.String(length=64), nullable=False),
    sa.Column('consentimiento_whatsapp_en', sa.DateTime(), nullable=True),
    sa.Column('ultimo_mensaje_entrante', sa.DateTime(), nullable=True),
    sa.Column('licitacion_activa', sa.String(length=40), nullable=True),
    sa.Column('analisis_activo_id', sa.Integer(), nullable=True),
    sa.Column('contexto_actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_rut'), ['rut'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_token_cuenta_hash'), ['token_cuenta_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_whatsapp'), ['whatsapp'], unique=False)

    op.create_table('licitaciones',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado_codigo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('organismo', sa.Text(), nullable=False),
    sa.Column('unidad', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('comuna', sa.String(length=120), nullable=False),
    sa.Column('monto_estimado', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('fecha_adjudicacion', sa.DateTime(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('clasificacion', sa.JSON(), nullable=True),
    sa.Column('clasificada_en', sa.DateTime(), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    with op.batch_alter_table('licitaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licitaciones_estado_codigo'), ['estado_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_licitaciones_fecha_cierre'), ['fecha_cierre'], unique=False)

    op.create_table('ordenes_compra',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=60), nullable=False),
    sa.Column('codigo_licitacion', sa.String(length=40), nullable=True),
    sa.Column('organismo', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('proveedor_rut', sa.String(length=20), nullable=False),
    sa.Column('proveedor_nombre', sa.Text(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('total_neto', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_compra_codigo_licitacion'), ['codigo_licitacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_fecha_envio'), ['fecha_envio'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_proveedor_rut'), ['proveedor_rut'], unique=False)

    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('codigo_producto', sa.String(length=20), nullable=False),
    sa.Column('producto', sa.Text(), nullable=False),
    sa.Column('unidad', sa.String(length=60), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('proveedor_rut', sa.String(length=20), nullable=False),
    sa.Column('proveedor_nombre', sa.Text(), nullable=False),
    sa.Column('organismo', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'referencia', 'posicion')
    )
    with op.batch_alter_table('precios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precios_codigo_producto'), ['codigo_producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_fecha'), ['fecha'], unique=False)

    op.create_table('analisis_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('licitacion_codigo', sa.String(length=40), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_salida', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id')
    )
    with op.batch_alter_table('analisis_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analisis_bases_licitacion_codigo'), ['licitacion_codigo'], unique=False)

    op.create_table('calces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('licitacion_codigo', sa.String(length=40), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('razon', sa.Text(), nullable=False),
    sa.Column('puntaje_prefiltro', sa.Float(), nullable=False),
    sa.Column('notificado', sa.Boolean(), nullable=False),
    sa.Column('notificado_en', sa.DateTime(), nullable=True),
    sa.Column('posicion_resumen', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['licitacion_codigo'], ['licitaciones.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'licitacion_codigo')
    )
    with op.batch_alter_table('calces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calces_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('mandatos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.String(length=64), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('periodicidad', sa.String(length=10), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('precio_fundador', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    with op.batch_alter_table('mandatos_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mandatos_pago_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mandatos_pago_mp_id'), ['mp_id'], unique=False)

    op.create_table('mensajes_whatsapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('wamid', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensajes_whatsapp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_whatsapp_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('periodicidad', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(), nullable=False),
    sa.Column('precio_fundador', sa.Boolean(), nullable=False),
    sa.Column('mandato_activo_id', sa.Integer(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('periodicidad', sa.String(length=10), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('mandato_id', sa.Integer(), nullable=False),
    sa.Column('mp_cobro_id', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.Column('factura_emitida', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['mandato_id'], ['mandatos_pago.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_cobro_id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_mandato_id'), ['mandato_id'], unique=False)

    op.create_table('solicitudes_analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis_bases.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'analisis_id')
    )
    with op.batch_alter_table('solicitudes_analisis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_analisis_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_analisis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_analisis_empresa_id'))

    op.drop_table('solicitudes_analisis')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_mandato_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_empresa_id'))

    op.drop_table('pagos')
    op.drop_table('suscripciones')
    with op.batch_alter_table('mensajes_whatsapp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_whatsapp_empresa_id'))

    op.drop_table('mensajes_whatsapp')
    with op.batch_alter_table('mandatos_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mandatos_pago_mp_id'))
        batch_op.drop_index(batch_op.f('ix_mandatos_pago_empresa_id'))

    op.drop_table('mandatos_pago')
    with op.batch_alter_table('calces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calces_empresa_id'))

    op.drop_table('calces')
    with op.batch_alter_table('analisis_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisis_bases_licitacion_codigo'))

    op.drop_table('analisis_bases')
    with op.batch_alter_table('precios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precios_fecha'))
        batch_op.drop_index(batch_op.f('ix_precios_codigo_producto'))

    op.drop_table('precios')
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_proveedor_rut'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_fecha_envio'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_codigo_licitacion'))

    op.drop_table('ordenes_compra')
    with op.batch_alter_table('licitaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licitaciones_fecha_cierre'))
        batch_op.drop_index(batch_op.f('ix_licitaciones_estado_codigo'))

    op.drop_table('licitaciones')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_whatsapp'))
        batch_op.drop_index(batch_op.f('ix_empresas_token_cuenta_hash'))
        batch_op.drop_index(batch_op.f('ix_empresas_rut'))

    op.drop_table('empresas')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_licitacion_codigo'))

    op.drop_table('documentos')
    # ### end Alembic commands ###
