"""datos de facturacion

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 06:16:10.544048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), server_default='', nullable=False))
        batch_op.add_column(sa.Column('comuna', sa.String(length=100), server_default='', nullable=False))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_folio', sa.String(length=20), server_default='', nullable=False))
        batch_op.add_column(sa.Column('factura_emitida_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_column('factura_emitida_en')
        batch_op.drop_column('factura_folio')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('comuna')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
