"""aviso de cobro rechazado por correo

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 13:20:13.808735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aviso_correo_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###
    # Los cobros rechazados que ya estaban resueltos no deben generar correos al publicar esta versión.
    op.execute("UPDATE pagos SET aviso_correo_en = aviso_enviado_en WHERE aviso_enviado_en IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_column('aviso_correo_en')

    # ### end Alembic commands ###
